# permissions for end users to edit messages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: message-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: message-controller
    app.kubernetes.io/part-of: message-controller
    app.kubernetes.io/managed-by: kustomize
  name: message-editor-role
rules:
- apiGroups:
  - message.example.com
  resources:
  - messages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - message.example.com
  resources:
  - messages/status
  verbs:
  - get
